### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'diffusers'

### ISSUE THREAD

**Issue by altoiddealer** [Panchovix/stable-diffusion-webui-forge#4]
### Checklist

- [X] The issue exists after disabling all extensions
- [X] The issue exists on a clean installation of webui
- [ ] The issue is caused by an extension, but I believe it is caused by a bug in the webui
- [ ] The issue exists in the current version of the webui
- [X] The issue has not been reported before recently
- [ ] The issue has been reported before but has not been fixed yet

### What happened?

After installing this branch clean in a new location, and running webui-user.bat to set up, it had this error and continues presenting it on every startup:

```
*** Error loading script: preprocessor_marigold.py
    Traceback (most recent call last):
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\modules\scripts.py", line 581, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\modules\script_loading.py", line 12, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\extensions-builtin\forge_preprocessor_marigold\scripts\preprocessor_marigold.py", line 10, in <module>
        from marigold.model.marigold_pipeline import MarigoldPipeline
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\extensions-builtin\forge_preprocessor_marigold\marigold\model\marigold_pipeline.py", line 9, in <module>
        from diffusers import (
    ModuleNotFoundError: No module named 'diffusers'
```

After installing my favorite extensions, I found that this error also affects one of my favorite extensions, layerdiffuse:

```
*** Error loading script: forge_layerdiffusion.py
    Traceback (most recent call last):
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\modules\scripts.py", line 581, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\modules\script_loading.py", line 12, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py", line 15, in <module>
        from lib_layerdiffusion.models import TransparentVAEDecoder, TransparentVAEEncoder
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\extensions\sd-forge-layerdiffuse\lib_layerdiffusion\models.py", line 8, in <module>
        from diffusers.configuration_utils import ConfigMixin, register_to_config
    ModuleNotFoundError: No module named 'diffusers'
```

### Steps to reproduce the problem

1. Clone the repo / branch
2. Run webui-user.bat

### What should have happened?

No error.

### What browsers do you use to access the UI ?

Google Chrome

### Sysinfo

[sysinfo-2024-07-09-16-58.json](https://github.com/user-attachments/files/16146874/sysinfo-2024-07-09-16-58.json)

### Console logs

```Shell
venv "D:\0_AI\stable-diffusion-webui-forge-a1111\venv\Scripts\Python.exe"
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-474-g7b74fe6c
Commit hash: 7b74fe6c3f2e1a0d32891b3952708955ee214957
CUDA 12.1
Installing forge_legacy_preprocessor requirement: changing opencv-python version from 4.10.0.84 to 4.8.0
Installing sd-forge-controlnet requirement: changing opencv-python version from 4.10.0.84 to 4.8.0
Launching Web UI with arguments:
Total VRAM 12282 MB, total RAM 32536 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Using pytorch cross attention
*** Error loading script: preprocessor_marigold.py
    Traceback (most recent call last):
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\modules\scripts.py", line 581, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\modules\script_loading.py", line 12, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\extensions-builtin\forge_preprocessor_marigold\scripts\preprocessor_marigold.py", line 10, in <module>
        from marigold.model.marigold_pipeline import MarigoldPipeline
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\extensions-builtin\forge_preprocessor_marigold\marigold\model\marigold_pipeline.py", line 9, in <module>
        from diffusers import (
    ModuleNotFoundError: No module named 'diffusers'

---
ControlNet preprocessor location: D:\0_AI\stable-diffusion-webui-forge-a1111\models\ControlNetPreprocessor
[-] ADetailer initialized. version: 24.6.0, num models: 10
*** Error loading script: forge_layerdiffusion.py
    Traceback (most recent call last):
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\modules\scripts.py", line 581, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\modules\script_loading.py", line 12, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py", line 15, in <module>
        from lib_layerdiffusion.models import TransparentVAEDecoder, TransparentVAEEncoder
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\extensions\sd-forge-layerdiffuse\lib_layerdiffusion\models.py", line 8, in <module>
        from diffusers.configuration_utils import ConfigMixin, register_to_config
    ModuleNotFoundError: No module named 'diffusers'

---
WARNING:dinov2:xFormers not available
WARNING:dinov2:xFormers not available
*** Error loading script: loractl.py
    Traceback (most recent call last):
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\modules\scripts.py", line 581, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\modules\script_loading.py", line 12, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\extensions\sd-webui-loractl\scripts\loractl.py", line 5, in <module>
        from loractl.lib import utils, plot, lora_ctl_network, network_patch
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\extensions\sd-webui-loractl\loractl\lib\plot.py", line 6, in <module>
        from loractl.lib.lora_ctl_network import networks
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\extensions\sd-webui-loractl\loractl\lib\lora_ctl_network.py", line 10, in <module>
        import network, networks, network_lora, extra_networks_lora
    ModuleNotFoundError: No module named 'network_lora'

---
12:51:38 - ReActor - STATUS - Running v0.7.1-a1 on Device: CUDA
Loading weights [15012c538f] from D:\0_AI\stable-diffusion-webui-forge-a1111\models\Stable-diffusion\realisticVisionV51_v51VAE.safetensors
2024-07-09 12:51:39,507 - ControlNet - INFO - ControlNet UI callback registered.
model_type EPS
UNet ADM Dimension 0
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 15.5s (prepare environment: 8.3s, import torch: 2.3s, import gradio: 0.5s, setup paths: 0.6s, other imports: 0.4s, load scripts: 2.2s, create ui: 0.9s, gradio launch: 0.2s).
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
To load target model SD1ClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  11037.63671875
[Memory Management] Model Memory (MB) =  454.2076225280762
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  9559.429096221924
Moving model(s) has taken 0.10 seconds
Model loaded in 4.0s (load weights from disk: 0.5s, forge load real models: 3.0s, calculate empty prompt: 0.4s).
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Version: f0.0.17v1.8.0rc-latest-474-g7b74fe6c
Commit hash: 7b74fe6c3f2e1a0d32891b3952708955ee214957
CUDA 12.1
Installing forge_legacy_preprocessor requirement: changing opencv-python version from 4.10.0.84 to 4.8.0
Installing sd-forge-controlnet requirement: changing opencv-python version from 4.10.0.84 to 4.8.0
Launching Web UI with arguments:
Total VRAM 12282 MB, total RAM 32536 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti : native
Hint: your device supports --pin-shared-memory for potential speed improvements.
Hint: your device supports --cuda-malloc for potential speed improvements.
Hint: your device supports --cuda-stream for potential speed improvements.
VAE dtype: torch.bfloat16
CUDA Stream Activated:  False
Using pytorch cross attention
*** Error loading script: preprocessor_marigold.py
    Traceback (most recent call last):
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\modules\scripts.py", line 581, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\modules\script_loading.py", line 12, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\extensions-builtin\forge_preprocessor_marigold\scripts\preprocessor_marigold.py", line 10, in <module>
        from marigold.model.marigold_pipeline import MarigoldPipeline
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\extensions-builtin\forge_preprocessor_marigold\marigold\model\marigold_pipeline.py", line 9, in <module>
        from diffusers import (
    ModuleNotFoundError: No module named 'diffusers'

---
ControlNet preprocessor location: D:\0_AI\stable-diffusion-webui-forge-a1111\models\ControlNetPreprocessor
[-] ADetailer initialized. version: 24.6.0, num models: 10
*** Error loading script: forge_layerdiffusion.py
    Traceback (most recent call last):
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\modules\scripts.py", line 581, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\modules\script_loading.py", line 12, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\extensions\sd-forge-layerdiffuse\scripts\forge_layerdiffusion.py", line 15, in <module>
        from lib_layerdiffusion.models import TransparentVAEDecoder, TransparentVAEEncoder
      File "D:\0_AI\stable-diffusion-webui-forge-a1111\extensions\sd-forge-layerdiffuse\lib_layerdiffusion\models.py", line 8, in <module>
        from diffusers.configuration_utils import ConfigMixin, register_to_config
    ModuleNotFoundError: No module named 'diffusers'

---
WARNING:dinov2:xFormers not available
WARNING:dinov2:xFormers not available
12:52:19 - ReActor - STATUS - Running v0.7.1-a1 on Device: CUDA
Loading weights [15012c538f] from D:\0_AI\stable-diffusion-webui-forge-a1111\models\Stable-diffusion\realisticVisionV51_v51VAE.safetensors
2024-07-09 12:52:20,175 - ControlNet - INFO - ControlNet UI callback registered.
model_type EPS
UNet ADM Dimension 0
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 15.1s (prepare environment: 8.3s, import torch: 2.3s, import gradio: 0.5s, setup paths: 0.6s, other imports: 0.4s, load scripts: 1.9s, create ui: 0.8s, gradio launch: 0.1s).
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
extra {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
To load target model SD1ClipModel
Begin to load 1 model
[Memory Management] Current Free GPU Memory (MB) =  11037.63671875
[Memory Management] Model Memory (MB) =  454.2076225280762
[Memory Management] Minimal Inference Memory (MB) =  1024.0
[Memory Management] Estimated Remaining GPU Memory (MB) =  9559.429096221924
Moving model(s) has taken 0.09 seconds
Model loaded in 3.2s (calculate hash: 0.2s, load weights from disk: 0.5s, forge load real models: 1.3s, load textual inversion embeddings: 1.0s, calculate empty prompt: 0.2s).
```

**Comment by Panchovix** [comment]
Checking the requirements and effectively seems diffusers isn't there, but it should install itself by the other libraries.

If you enable the venv (.\venv\Scripts\activate) on the folder, then `pip install diffusers==0.25.0`, and then open the bat again, does it work?

**Comment by altoiddealer** [comment]
> Checking the requirements and effectively seems diffusers isn't there, but it should install itself by the other libraries.
> 
> If you enable the venv (.\venv\Scripts\activate) on the folder, then `pip install diffusers==0.25.0`, and then open the bat again, does it work?

This worked!

I've never had this issue when installing A1111 / Forge and I've installed them many times.

**Comment by Panchovix** [comment]
> > Checking the requirements and effectively seems diffusers isn't there, but it should install itself by the other libraries.
> > If you enable the venv (.\venv\Scripts\activate) on the folder, then `pip install diffusers==0.25.0`, and then open the bat again, does it work?
> 
> This worked!
> 
> I've never had this issue when installing A1111 / Forge and I've installed them many times.

Pretty interesting, gonna add as requirement in any case, thanks for your report!
